---
abstract: unknown
author:
  - unknown
build_requires:
  Digest::SHA: 0
  Mojolicious: 3.20
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex-Endpoint-HTTP
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 3.20
resources:
  repository: https://github.com/krimdomu/rex-endpoint-http
version: v0.35.0
